CSHARP/OENIK_PROG3_2019_2_C0T9T9/MyCinema.Web/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCinema.Web.Models
{

    public class Film
    {
        [Display(Name = "Film id")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Film title")]
        [Required]
        public string Cim { get; set; }

        [Display(Name = "Film genre")]
        [Required]
        public string Mufaj { get; set; }

        [Display(Name = "Film length")]
        [Required]
        public int Hossz { get; set; }

        [Display(Name = "Film release year")]
        [Required]
        public int Ev { get; set; }

        [Display(Name = "Main actor")]
        [Required]
        public string Foszereplo { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_C0T9T9/MyCinema.Web/Models/FilmViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyCinema.Web.Models
{
    public class FilmViewModel
    {
        public Film EditedFilm { get; set; }
        public List<Film> ListOfFilms { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_C0T9T9/MyCinema.Web/Controllers/FilmController.cs
using AutoMapper;
using MyCinema.Data;
using MyCinema.Logic;
using MyCinema.Repository;
using MyCinema.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyCinema.Web.Controllers
{
    public class FilmController : Controller
    {
        IFilmLogic logic;
        IMapper mapper;
        FilmViewModel model;

        public FilmController()
        {
            MyCinemaDatabaseEntities ctx = new MyCinemaDatabaseEntities();
            FilmRepository filmRepo = new FilmRepository();
            logic = new FilmLogic(filmRepo);
            mapper = MapperFactory.CreateMapper();
            model = new FilmViewModel();
            model.EditedFilm = new Models.Film();

            var films = logic.GetFilms();
            model.ListOfFilms = mapper.Map<IList<Data.Film>, List<Models.Film>>(films);
        }

        private Models.Film GetFilmModel(int id)
        {
            Data.Film oneFilm = logic.GetFilmByID(id);
            return mapper.Map<Data.Film, Models.Film>(oneFilm);
        }

        // GET: Film
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("FilmIndex", model);
        }

        public ActionResult Details(int id)
        {
            return View("FilmDetails", GetFilmModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.DeleteFilm(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            model.EditedFilm = GetFilmModel(id);
            return View("FilmIndex", model);
        }

        [HttpPost]
        public ActionResult Edit(Models.Film film, string editAction)
        {
            if (ModelState.IsValid && film != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.CreateFilm(new Data.Film() { cim = film.Cim, mufaj = film.Mufaj, hossz = film.Hossz, ev = film.Ev, foszereplo = film.Foszereplo });
                }
                else
                {
                    if (!logic.ChangeFilm(film.Id, film.Cim, film.Mufaj, film.Hossz, film.Ev, film.Foszereplo))
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                model.EditedFilm = film;
                return View("CarsIndex", model);
            }
        }

    }
}

CSHARP/OENIK_PROG3_2019_2_C0T9T9/MyCinema.Web/Views/Film/FilmDetails.cshtml
@model MyCinema.Web.Models.Film
@{
    ViewBag.Title = "FilmDetails";
}

<h2>Datasheet of one movie</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Cim)</td>
        <td>@Html.DisplayFor(m => m.Cim)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Mufaj)</td>
        <td>@Html.DisplayFor(m => m.Mufaj)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Hossz)</td>
        <td>@Html.DisplayFor(m => m.Hossz)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Ev)</td>
        <td>@Html.DisplayFor(m => m.Ev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Foszereplo)</td>
        <td>@Html.DisplayFor(m => m.Foszereplo)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_C0T9T9/MyCinema.Web/Views/Film/FilmEdit.cshtml
@model MyCinema.Web.Models.Film
@{
    ViewBag.Title = "FilmEdit";
}

<h2>Edit one movie</h2>

@using (Html.BeginForm("Edit", "Film"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Cim)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Cim)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Mufaj)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Mufaj)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Hossz)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Hossz)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Ev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Ev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Foszereplo)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Foszereplo)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_2_C0T9T9/MyCinema.Web/Views/Film/FilmIndex.cshtml
@model MyCinema.Web.Models.FilmViewModel

@{
    ViewBag.Title = "Crud Index";
}

<h2>Films Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@Html.Partial("FilmEdit", Model.EditedFilm)

@Html.Partial("FilmList", Model.ListOfFilms)

CSHARP/OENIK_PROG3_2019_2_C0T9T9/MyCinema.Web/Views/Film/FilmList.cshtml
@model IEnumerable<MyCinema.Web.Models.Film>

@{
    ViewBag.Title = "FilmList";
}

<h2>List of films</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database! :(</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Cim)</th>
            <th>@Html.DisplayNameFor(m => m.First().Mufaj)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Cim)</td>
                <td>@Html.DisplayFor(m => item.Mufaj)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}